/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tpws;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mr SOFIANE
 */
public class Client extends javax.swing.JFrame {
    
    /*void update_table() throws SQLException, ClassNotFoundException{
        
            ResultSet resultat = stmt.executeQuery("SELECT * FROM client");
            table.setModel(DbUtils.resultSetToTableModel(resultat));
            
        }*/
    

    /**
     * Creates new form JF1
     */
  ButtonGroup bg =new ButtonGroup();
     
    public Client() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setTitle("Gestion des clients");
        bg.add(rd2);
        bg.add(rd1);
        
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jtf1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtf2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtf3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jtf4 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jtf0 = new javax.swing.JTextField();
        rd1 = new javax.swing.JRadioButton();
        rd2 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        ID = new javax.swing.JLabel();
        jtf10 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jtf11 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtf12 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtf13 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jtf14 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 500));

        btn.setText("Accueil");
        btn.setToolTipText("");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        jPanel1.add(btn);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajouter client"));
        jPanel8.setLayout(new java.awt.GridLayout(9, 0));

        jLabel11.setText("Nom");
        jPanel8.add(jLabel11);

        jtf1.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel8.add(jtf1);

        jLabel12.setText("Ville");
        jPanel8.add(jLabel12);
        jPanel8.add(jtf2);

        jLabel13.setText("RC");
        jPanel8.add(jLabel13);
        jPanel8.add(jtf3);

        jLabel14.setText("Matricule fiscal");
        jPanel8.add(jLabel14);
        jPanel8.add(jtf4);

        jButton9.setText("Ajouter");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton9);

        jButton10.setText("Vider");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton10);

        jPanel8.add(jPanel10);

        jPanel2.add(jPanel8, java.awt.BorderLayout.LINE_START);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Rechercher un client"));
        jPanel9.setLayout(new java.awt.BorderLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N° Client", "Nom", "Ville", "RC", "Matricule fiscale"
            }
        ));
        table.setMinimumSize(new java.awt.Dimension(300, 300));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel9.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel12.setLayout(new java.awt.GridLayout(2, 0));

        jtf0.setMinimumSize(new java.awt.Dimension(10, 20));
        jtf0.setPreferredSize(new java.awt.Dimension(160, 25));
        jPanel4.add(jtf0);

        rd1.setSelected(true);
        rd1.setText("Nom");
        rd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd1ActionPerformed(evt);
            }
        });
        jPanel4.add(rd1);

        rd2.setText("Ville");
        rd2.setToolTipText("");
        jPanel4.add(rd2);

        jPanel12.add(jPanel4);

        jButton13.setText("Rechercher");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton13);

        jButton1.setText("Supprimer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);

        jPanel12.add(jPanel5);

        jPanel9.add(jPanel12, java.awt.BorderLayout.PAGE_END);

        jPanel2.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Mise à jour"));
        jPanel3.setLayout(new java.awt.GridLayout(11, 0));

        ID.setText("ID");
        jPanel3.add(ID);

        jtf10.setEnabled(false);
        jPanel3.add(jtf10);

        jLabel15.setText("Nom");
        jPanel3.add(jLabel15);

        jtf11.setPreferredSize(new java.awt.Dimension(150, 20));
        jtf11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf11ActionPerformed(evt);
            }
        });
        jPanel3.add(jtf11);

        jLabel16.setText("Ville");
        jPanel3.add(jLabel16);
        jPanel3.add(jtf12);

        jLabel17.setText("RC");
        jPanel3.add(jLabel17);
        jPanel3.add(jtf13);

        jLabel18.setText("Matricule fiscal");
        jPanel3.add(jLabel18);
        jPanel3.add(jtf14);

        jButton11.setText("Mettre à jour");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11);

        jPanel2.add(jPanel3, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        // TODO add your handling code here:
        Login log = new Login();
        log.setVisible(true);        
        dispose();

    }//GEN-LAST:event_btnActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
            DBC con = null;
            Statement stmt = null;
        try{
            String req=null;
            con = new DBC();
            stmt=con.getConnection().createStatement();
            
            if(rd1.isSelected()){
                req = "SELECT * FROM client WHERE nom LIKE '%"+jtf0.getText()+"%'" ;
            }if(rd2.isSelected()){
                req = "SELECT * FROM client WHERE ville LIKE '%"+jtf0.getText()+"%'" ;
            }
            ResultSet resultat = stmt.executeQuery(req);
            table.setModel(DbUtils.resultSetToTableModel(resultat));
                                int i=0 ;
                              
				while(resultat.next()){
				table.setValueAt(resultat.getString("n_client"), i, 0);
				table.setValueAt(resultat.getString("nom"), i, 1);
				table.setValueAt(resultat.getString("ville"), i, 2);
				table.setValueAt(resultat.getString("rc"), i, 3);
				table.setValueAt(resultat.getString("mat_fiscal"), i, 4);
				i++;
				}
       }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        DBC con = null;
            Statement stmt = null;
        try{
            con = new DBC();
            stmt=con.getConnection().createStatement();
            stmt.executeUpdate("INSERT INTO client VALUES (NULL,'"+jtf1.getText()+"','"+jtf2.getText()+"','"+jtf3.getText()+"','"+jtf4.getText()+"')");
            JOptionPane.showMessageDialog(null, "Client ajouté avec succès", "Information", JOptionPane.ERROR_MESSAGE);
            jtf1.setText("");jtf2.setText("");jtf3.setText("");jtf4.setText("");
            ResultSet resultat = stmt.executeQuery("SELECT * FROM client");
            table.setModel(DbUtils.resultSetToTableModel(resultat));
            
       }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        jtf1.setText("");jtf2.setText("");jtf3.setText("");jtf4.setText("");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            DBC con = null;
            Statement stmt = null;
        try{
            con = new DBC();
            stmt=con.getConnection().createStatement();
            stmt.executeUpdate("DELETE FROM client WHERE n_client='"+table.getValueAt(table.getSelectedRow(), 0)+"'");
            JOptionPane.showMessageDialog(null, "Client supprimé avec succès", "Information", JOptionPane.ERROR_MESSAGE);
            
            ResultSet resultat = stmt.executeQuery("SELECT * FROM client");
            table.setModel(DbUtils.resultSetToTableModel(resultat));
            jtf10.setText("");jtf11.setText("");jtf12.setText("");jtf13.setText("");jtf14.setText("");

       }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtf11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf11ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        DBC con = null;
        Statement stmt = null;
        try{
            con = new DBC();
            stmt=con.getConnection().createStatement();
            stmt.executeUpdate("UPDATE client Set nom ='"+jtf11.getText()+"',ville ='"+jtf12.getText()+"',rc ='"+jtf13.getText()+"',mat_fiscal ='"+jtf14.getText()+"' WHERE n_client = '"+jtf10.getText()+"' ");
            JOptionPane.showMessageDialog(null, "Client màj avec succès", "Information", JOptionPane.ERROR_MESSAGE);
            ResultSet resultat = stmt.executeQuery("SELECT * FROM client");
            table.setModel(DbUtils.resultSetToTableModel(resultat));
            jtf10.setText("");jtf11.setText("");jtf12.setText("");jtf13.setText("");jtf14.setText("");

        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        
            jtf10.setText(String.valueOf( table.getValueAt(table.getSelectedRow(), 0)));
            jtf11.setText((String) table.getValueAt(table.getSelectedRow(), 1));
            jtf12.setText((String) table.getValueAt(table.getSelectedRow(), 2));
            jtf13.setText((String) table.getValueAt(table.getSelectedRow(), 3));
            jtf14.setText(String.valueOf( table.getValueAt(table.getSelectedRow(), 4)));
        
    }//GEN-LAST:event_tableMouseClicked

    private void rd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rd1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JButton btn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtf0;
    private javax.swing.JTextField jtf1;
    public javax.swing.JTextField jtf10;
    public javax.swing.JTextField jtf11;
    public javax.swing.JTextField jtf12;
    public javax.swing.JTextField jtf13;
    public javax.swing.JTextField jtf14;
    private javax.swing.JTextField jtf2;
    private javax.swing.JTextField jtf3;
    private javax.swing.JTextField jtf4;
    private javax.swing.JRadioButton rd1;
    private javax.swing.JRadioButton rd2;
    public javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
