/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tpws;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mr SOFIANE
 */
public class Nligne extends javax.swing.JFrame {

    /**
     * Creates new form Ncommande
     */
    String req = "INSERT INTO ligne_commande VALUES ";
    boolean virgule = false;
    double mant=0 ;
    String ncommande = null;

    public Nligne() {
        initComponents();
        filcombo();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setTitle("Ajouter une ligne de commande");
    }
    private void filcombo(){
        DBC con = null;
            Statement stmt = null;
        try{
            con = new DBC();
            stmt=con.getConnection().createStatement();
            
            
            ResultSet resultat = stmt.executeQuery("SELECT libelle FROM article");
                              
				while(resultat.next()){
                                String name = resultat.getString("libelle");
				cb.addItem(name);
				
				}
       }catch(Exception e){
            e.printStackTrace();
        }}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cb = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 350));
        setPreferredSize(new java.awt.Dimension(450, 350));

        jPanel1.setLayout(new java.awt.GridLayout(3, 1));

        jLabel1.setText("Article");
        jPanel3.add(jLabel1);

        cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selectionner un article" }));
        jPanel3.add(cb);

        jPanel1.add(jPanel3);

        jLabel2.setText("Quantité");
        jPanel4.add(jLabel2);

        tf1.setPreferredSize(new java.awt.Dimension(150, 30));
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        jPanel4.add(tf1);

        jPanel1.add(jPanel4);

        jButton1.setText("Insérer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);

        jPanel1.add(jPanel5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jButton3.setText("Valider");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton3);

        getContentPane().add(jPanel6, java.awt.BorderLayout.PAGE_END);

        jPanel7.setLayout(new java.awt.BorderLayout());

        ta.setEditable(false);
        ta.setColumns(20);
        ta.setRows(5);
        jScrollPane1.setViewportView(ta);

        jPanel7.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DBC con = null;
        Statement stmt = null;
        String narticle = null;
        String prix = null;
        try{
            con = new DBC();
            stmt=con.getConnection().createStatement();
            
            ResultSet resultat = stmt.executeQuery("SELECT MAX(n_commande) AS max FROM commande");
				while(resultat.next()){
				ncommande = resultat.getString("max");			
				}
                                ResultSet res = stmt.executeQuery("SELECT n_article,prix_unit FROM article where libelle = '"+cb.getSelectedItem()+"'");
                                while(res.next()){
				narticle = res.getString("n_article");
                                prix = res.getString("prix_unit");
				}
       }catch(Exception e){
            e.printStackTrace();
        }
        
        int qt = Integer.parseInt(tf1.getText());
        double pri = Double.parseDouble(prix);
        double montant = pri*qt;
        mant = mant+montant;
        System.out.println(mant);
        if(virgule == false){
        req = req+"('"+ncommande+"','"+narticle+"','"+prix+"','"+tf1.getText()+"','"+montant+"')";
                virgule = true;
                JOptionPane.showMessageDialog(null, "Ligne ajoutée avec succès", "Information", JOptionPane.ERROR_MESSAGE);

        }else {req = req+",('"+ncommande+"','"+narticle+"','"+prix+"','"+tf1.getText()+"','"+montant+"')"; 
                    JOptionPane.showMessageDialog(null, "Ligne ajoutée avec succès", "Information", JOptionPane.ERROR_MESSAGE);
        }
        ta.setText(ta.getText()+"\n Article : "+cb.getSelectedItem()+" Quantité : "+tf1.getText());
                        tf1.setText("");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DBC con = null;
            Statement stmt = null;
        try{
            con = new DBC();
            stmt=con.getConnection().createStatement();
            stmt.executeUpdate(req);
            stmt.executeUpdate("UPDATE commande set montant_com = '"+mant+"' where n_commande= '"+ncommande+"'");
            JOptionPane.showMessageDialog(null, "Commande ajouté avec succès", "Information", JOptionPane.ERROR_MESSAGE);
            
       }catch(Exception e){
            e.printStackTrace();
        }
        dispose();
        Commande cm = new Commande();
        cm.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nligne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nligne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nligne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nligne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nligne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta;
    private javax.swing.JTextField tf1;
    // End of variables declaration//GEN-END:variables
}
