/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tpws;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Mr SOFIANE
 */
public class Ravance extends javax.swing.JFrame {
    public String nom,ville,date; 

    /**
     * Creates new form Ravance
     */
    public Ravance() {
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setTitle("Rechercher une commande");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        calender = new com.github.lgooddatepicker.components.CalendarPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        text1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        text2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 280));

        jButton1.setText("Rechercher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);

        getContentPane().add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Date commande"));
        jPanel7.setLayout(new java.awt.BorderLayout());
        jPanel7.add(calender, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel7, java.awt.BorderLayout.LINE_START);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Informations du client"));
        jPanel8.setLayout(new java.awt.GridLayout(4, 0));

        jLabel1.setText("Nom");
        jPanel8.add(jLabel1);
        jPanel8.add(text1);

        jLabel2.setText("Ville");
        jPanel8.add(jLabel2);
        jPanel8.add(text2);

        jPanel6.add(jPanel8, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Commande c ;
    public void set(Commande c){
    this.c = c;
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DBC con = null;
            Statement stmt = null;
        try{
            con = new DBC();
            stmt=con.getConnection().createStatement();
            
            ResultSet resultat = stmt.executeQuery("SELECT commande.n_commande,commande.n_client,commande.date_facture,commande.montant_com FROM client,commande WHERE client.nom LIKE '%"+text1.getText()+"%' AND client.ville LIKE '%"+text2.getText()+"%' AND client.n_client = commande.n_client AND commande.date_facture = '"+calender.getSelectedDate()+"'");
            c.table1.setModel(DbUtils.resultSetToTableModel(resultat));
                                int i=0 ;
				while(resultat.next()){
				c.table1.setValueAt(resultat.getString("n_commande"), i, 0);
				c.table1.setValueAt(resultat.getString("n_client"), i, 1);
				c.table1.setValueAt(resultat.getString("date_facture"), i, 2);
                                c.table1.setValueAt(resultat.getString("montant_com"), i, 3);
				i++;
				}
       }catch(Exception e){
            e.printStackTrace();
        }
        c.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ravance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ravance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ravance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ravance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ravance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.github.lgooddatepicker.components.CalendarPanel calender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    public javax.swing.JTextField text1;
    public javax.swing.JTextField text2;
    // End of variables declaration//GEN-END:variables
}
